import {test,expect} from '@playwright/test';
const entries={playground:[-27,0,33],slide:[-32,0,3],swing:[0,0,32],seesaw:[28,0,33],coaster:[-29,0,-26],bumper:[32,0,2],wheel:[28,0,-28],surf:[97,0,12],speedboat:[99,0,-14],parasail:[99,0,-35],snorkel:[99,0,22],scuba:[99,0,-26],skydive:[1.8,25.1,-81.2],trail:[0,0,-62],waterboom:[-47,0,-11],cable:[-16,1,-48.5]};
test('opening, branching story, settings and save/continue work',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>localStorage.setItem('adventure-park-settings',JSON.stringify({quality:'low',volume:0,reduced:true})));await page.goto('/');await expect(page.locator('body')).toHaveAttribute('data-state','menu');
  await page.locator('#new-game').click();await expect(page.locator('body')).toHaveAttribute('data-state','intro');await page.keyboard.press('Enter');await expect(page.locator('#dialogue')).toBeVisible();await page.locator('#next').click();await page.getByRole('button',{name:'Wonder Wheel',exact:true}).click();await page.locator('#next').click();await expect(page.locator('body')).toHaveAttribute('data-state','explore');await expect(page.locator('#objective')).toContainText('Wonder Wheel');
  await page.keyboard.press('ArrowUp');await page.keyboard.press('Space');await page.locator('#pause').click();await expect(page.locator('body')).toHaveAttribute('data-state','pause');await page.locator('#pause-settings').click();await page.locator('#quality').selectOption('low');await page.locator('#settings-back').click();await page.locator('#quit').click();await expect(page.locator('#continue')).toBeEnabled();await page.locator('#continue').click();await expect(page.locator('body')).toHaveAttribute('data-state','explore');expect(errors).toEqual([]);
});
for(const [id,position] of Object.entries(entries))test(`${id} can be boarded and exited safely`,async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(({position})=>{localStorage.setItem('adventure-park-save-v1',JSON.stringify({version:1,position,visited:[]}));localStorage.setItem('adventure-park-settings',JSON.stringify({quality:'low',volume:0,reduced:true}));},{position});
  await page.goto('/');await expect(page.locator('#continue')).toBeEnabled();await page.locator('#continue').click();await expect(page.locator('#prompt')).toBeVisible();await page.keyboard.press('Enter');await expect(page.locator('body')).toHaveAttribute('data-state','ride');await expect(page.locator('#ride-title')).not.toBeEmpty();await page.waitForTimeout(1200);await page.keyboard.press('Escape');await expect(page.locator('body')).toHaveAttribute('data-state','explore');await expect(page.locator('#prompt')).toBeVisible();expect(errors).toEqual([]);
});
