export const $=id=>document.getElementById(id);
export class UI {
  constructor(){this.touch=matchMedia('(pointer:coarse)').matches;this.lines=[];this.choiceCallback=null;this.done=null;this.toastTimer=null;}
  state(state){document.body.dataset.state=state;for(const id of ['menu','pause-menu','dialogue'])$(id).hidden=true;const map={menu:'menu',pause:'pause-menu',dialogue:'dialogue'};if(map[state])$(map[state]).hidden=false;$('hud').hidden=!['explore','ride'].includes(state);$('controls-hint').hidden=state!=='explore';$('touch').hidden=!this.touch||!['explore','ride'].includes(state);$('ride-caption').hidden=state!=='ride';$('prompt').hidden=true;document.body.classList.toggle('cinematic',['intro','ride','dialogue'].includes(state));if(document.activeElement instanceof HTMLElement)document.activeElement.blur();}
  prompt(ride){$('prompt').hidden=!ride;if(ride)$('prompt').querySelector('span').textContent=`Play · ${ride.name}`;}
  objective(text){$('objective').textContent=text;}
  toast(text){clearTimeout(this.toastTimer);$('toast').textContent=text;$('toast').hidden=false;this.toastTimer=setTimeout(()=>$('toast').hidden=true,4500);}
  dialogue(lines,done){this.lines=[...lines];this.done=done;this.next();}
  next(){const line=this.lines.shift();if(!line){this.done?.();return;}$('speaker').textContent=line.speaker;$('line').textContent=line.text;$('choices').replaceChildren();$('next').hidden=Boolean(line.choices);if(line.choices){for(const choice of line.choices){const b=document.createElement('button');b.textContent=choice.label;b.onclick=()=>{choice.choose();this.next();};$('choices').append(b);}$('choices').firstElementChild?.focus();}}
  ride(ride){$('ride-title').textContent=ride.name;$('emotion').textContent=ride.character?.emotion||'Excited';$('ride-hint').textContent=ride.elapsed<ride.boarding?'All aboard. Settle in…':ride.id==='bumper'?'↑ ↓ Accelerate / reverse · ← → Steer · ESC Exit':['swing','seesaw'].includes(ride.id)?'↑ ↓ Add momentum · ESC Exit':['waterboom'].includes(ride.id)?'Hold on tight — splashdown ahead · ESC Exit':['cable'].includes(ride.id)?'Ride the loop over the peaks · ESC Exit':['skydive'].includes(ride.id)?'Climb in… then leap · ESC Exit':'Enjoy the view · ESC Exit';}}
